[package]
name = "fdb-stacktester"
version = "0.1.0"
edition = "2018"

[features]
default = []
fdb-6_3 = ["fdb/fdb-6_3"]

[dependencies]
bytes = "1"
fdb = { version = "0.1.0", path = "../fdb", default-features = false }
tokio = { version = "1", features = ["full"] }