//! Provides [`FdbError`] type, [`FdbResult`] type alias and error
//! constants.

use std::error::Error;
use std::fmt::{self, Display};

/// Error type for this crate.
///
/// Internally it wraps FDB [Error Codes]. Error codes from 100 thru'
/// 999 is generated by the binding layer and not the C API.
///
/// [Error Codes]: https://apple.github.io/foundationdb/api-error-codes.html
//
// NOTE: 0 cannot be used for `error_code`.
//
// 100 - `database` module
// 110 - `transaction` module
// 120 - `tuple` module
// 130 - `subspace` module
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct FdbError {
    /// FoundationDB error code `fdb_error_t`
    error_code: i32,
}

/// Error occurred while opening database.
pub const DATABASE_OPEN: i32 = 100;

/// Error occured while trying to add read conflict key.
pub const TRANSACTION_ADD_READ_CONFLICT_KEY_IF_NOT_SNAPSHOT: i32 = 110;

/// Error occured while trying to add read conflict range.
pub const TRANSACTION_ADD_READ_CONFLICT_RANGE_IF_NOT_SNAPSHOT: i32 = 111;

/// Error occurred while getting a value from the tuple.
pub const TUPLE_GET: i32 = 120;

/// Error occurred extracting a [`Tuple`] value from [`Bytes`].
///
/// [`Tuple`]: crate::tuple::Tuple
/// [`Bytes`]: bytes::Bytes
pub const TUPLE_FROM_BYTES: i32 = 121;

/// Error occured when trying to pack [`Tuple`] containing an
/// incomplete [`Versionstamp`]. No incomplete [`Versionstamp`] found.
///
/// [`Tuple`]:  crate::tuple::Tuple
/// [`Versionstamp`]: crate::tuple::Versionstamp
pub const TUPLE_PACK_WITH_VERSIONSTAMP_NOT_FOUND: i32 = 122;

/// Error occured when trying to pack [`Tuple`] containing an
/// incomplete [`Versionstamp`]. Multiple incomplete [`Versionstamp`]
/// found.
///
/// [`Tuple`]:  crate::tuple::Tuple
/// [`Versionstamp`]: crate::tuple::Versionstamp
pub const TUPLE_PACK_WITH_VERSIONSTAMP_MULTIPLE_FOUND: i32 = 123;

/// Error occurred when calling [`strinc`], as the `prefix` supplied
/// is either empty or contains only `0xFF`.
///
/// [`strinc`]: crate::tuple::bytes_util::strinc
pub const TUPLE_BYTES_UTIL_STRINC_ERROR: i32 = 124;

/// Error occured when trying to pack [`Subspace`] containing an
/// incomplete [`Versionstamp`]. Prefix contains an incomplete
/// [`Versionstamp`], which is not allowed.
///
/// [`Subspace`]:  crate::subspace::Subspace
/// [`Versionstamp`]: crate::tuple::Versionstamp
pub const SUBSPACE_PACK_WITH_VERSIONSTAMP_PREFIX_INCOMPLETE: i32 = 130;

/// Error occured when trying to unpack a key. The provided key is not
/// contained in the [`Subspace`].
///
/// [`Subspace`]:  crate::subspace::Subspace
pub const SUBSPACE_UNPACK_KEY_MISMATCH: i32 = 131;

/// Alias for [`Result`]`<T,`[`FdbError`]`>`
///
/// [`Result`]: std::result::Result
/// [`FdbError`]: crate::error::FdbError
pub type FdbResult<T> = Result<T, FdbError>;

impl FdbError {
    /// Create new [`FdbError`]
    ///
    /// # Note
    ///
    /// You should not need to use this API. It is exposed publicly
    /// because we need to use it in binding tester. Otherwise, it is
    /// an internal API for this crate.
    pub fn new(err: fdb_sys::fdb_error_t) -> FdbError {
        FdbError {
            error_code: err as i32,
        }
    }

    /// Returns raw FDB error code
    pub fn code(self) -> i32 {
        self.error_code
    }

    /// Returns `true` if the error is from a layer. Returns `false`
    /// if the error is a [C binding] error
    ///
    /// [C binding]: https://apple.github.io/foundationdb/api-error-codes.html
    pub(crate) fn layer_error(e: i32) -> bool {
        (100..=999).contains(&e)
    }
}

impl Error for FdbError {}

impl Display for FdbError {
    fn fmt<'a>(&self, f: &mut fmt::Formatter<'a>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

/// Converts `fdb_error_t` to `FdbResult`
pub(crate) fn check(err: fdb_sys::fdb_error_t) -> FdbResult<()> {
    if err == 0 {
        Ok(())
    } else {
        Err(FdbError::new(err))
    }
}
